CATEGORY_WEIGHTS = {
    "DOCUMENTATION": 1.5,
    "ARCHITECTURE": 1.5,
    "TESTING": 1.5,
    "CICD": 1.5,
    "SECURITY": 1.0,
    "DEPENDENCIES": 1.0,
    "COMMUNITY_HEALTH": 1.0,
    "DEVELOPER_EXPERIENCE": 1.0
}
